# pubspec.yaml

name: javerage_timer
description: Un temporizador funcional basado en BLoC y Arquitectura Limpia.

publish_to: 'none' 

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  # Utilities
  equatable: ^2.0.5
  
  # UI/Visuals y Audio
  wave: ^0.2.2 
  audioplayers: ^5.2.1 
  lottie: ^3.0.0 # ðŸ‘ˆ PAQUETE PARA EL SPLASH ANIMADO

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  flutter_launcher_icons: "^0.13.1" # ðŸ‘ˆ HERRAMIENTA PARA EL ÃCONO DE LA APP

flutter:
  uses-material-design: true
  
  # DeclaraciÃ³n de todos los directorios de assets
  assets:
    - assets/audio/
    - assets/lottie/ # ðŸ‘ˆ Directorio para la animaciÃ³n JSON
    - assets/icon/   # ðŸ‘ˆ Directorio para el icono PNG

# ðŸ‘ˆ CONFIGURACIÃ“N PARA EL LANZADOR (LAUNCHER ICON)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png" # AsegÃºrate que tu PNG estÃ© aquÃ­
  min_sdk_android: 21